function result = KullbackLeiblerGam(a1,b1,a2,b2)

% result = (cq-1).*psi(cq)-log(bq)-cq-gammaln(cq)+...
%          gammaln(cp)+cp.*log(bp)-...
%         (cp-1).*(psi(cq)+log(bq))+(bq.*cq)./bp;


result = (a1 - 1).*psi(a1) - log(b1) - a1 - gammaln(a1) + ...
          gammaln(a2) + a2 .* log(b2) - ...
         (a2 -1).*(psi(a1)+log(b1))+(b1.*a1./b2);
